USE [master]
GO

/****** Object:  Database [onlinebanking]    Script Date: 18-11-2021 18:14:30 ******/
CREATE DATABASE [onlinebanking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'onlinebanking', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\onlinebanking.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'onlinebanking_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\onlinebanking_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [onlinebanking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [onlinebanking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [onlinebanking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [onlinebanking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [onlinebanking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [onlinebanking] SET ARITHABORT OFF 
GO

ALTER DATABASE [onlinebanking] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [onlinebanking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [onlinebanking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [onlinebanking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [onlinebanking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [onlinebanking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [onlinebanking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [onlinebanking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [onlinebanking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [onlinebanking] SET  ENABLE_BROKER 
GO

ALTER DATABASE [onlinebanking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [onlinebanking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [onlinebanking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [onlinebanking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [onlinebanking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [onlinebanking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [onlinebanking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [onlinebanking] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [onlinebanking] SET  MULTI_USER 
GO

ALTER DATABASE [onlinebanking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [onlinebanking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [onlinebanking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [onlinebanking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [onlinebanking] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [onlinebanking] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [onlinebanking] SET QUERY_STORE = OFF
GO

ALTER DATABASE [onlinebanking] SET  READ_WRITE 
GO

